"use client";

/**
 * TakeoffMoment — Phase 43.5 (2026-05-21).
 *
 * Replaces the §5 placeholder testimonial ("we're building in public,
 * a real one will land here") with a launch moment that visually
 * tees up the pricing section. The fake quote was honest dead air;
 * the takeoff turns it into anticipation.
 *
 * Concept (Marc's pick, "Yes — pebble-logo rocket SVG animation"):
 * the round Pebble brand mark is the rocket. On scroll-into-view
 * the pebble lifts off the bottom of the section and rises out the
 * top, leaving a vertical vapor trail behind it. The trail + a
 * pulsing downward chevron creates visual gravity that pulls the
 * eye straight down into the pricing grid below.
 *
 * No auto-scroll — on iOS scroll-jacking-without-user-intent is
 * jarring and breaks the scroll position. The animation gives the
 * "you should keep going" cue; the user does the actual scrolling.
 *
 * Background is a pre-dawn launch gradient (deep indigo top → soft
 * blue middle → cream bottom) with a sparse starfield in the dark
 * portion. Pure SVG + Framer Motion — no video assets, no Lottie.
 */

import React from "react";
import { motion, useReducedMotion } from "framer-motion";
import { ChevronDown } from "lucide-react";
import { cn } from "@/lib/utils";

const EASE = [0.22, 1, 0.36, 1] as const;
const LAUNCH_MS = 2200;
const TEXT_DELAY_MS = 200;

/* ----------------------------- starfield ------------------------------- */

/** Deterministic star positions so SSR + client render the same dots
    (the rocket scene mostly fills the upper portion). Generated by hand
    instead of random — 28 stars at varying sizes feels intentional. */
type Star = { x: number; y: number; size: number; o: number };
const STARS: Star[] = [
  { x:  4, y:  8, size: 1.5, o: 0.7 },
  { x: 12, y: 18, size: 1,   o: 0.5 },
  { x: 18, y:  4, size: 2,   o: 0.85 },
  { x: 26, y: 22, size: 1,   o: 0.4 },
  { x: 32, y: 12, size: 1.5, o: 0.65 },
  { x: 38, y:  6, size: 1,   o: 0.5 },
  { x: 44, y: 18, size: 2,   o: 0.8 },
  { x: 52, y: 10, size: 1,   o: 0.5 },
  { x: 58, y: 20, size: 1.5, o: 0.7 },
  { x: 64, y:  4, size: 1,   o: 0.4 },
  { x: 70, y: 14, size: 2.5, o: 0.9 },
  { x: 76, y:  8, size: 1,   o: 0.5 },
  { x: 82, y: 22, size: 1.5, o: 0.6 },
  { x: 88, y: 12, size: 1,   o: 0.45 },
  { x: 94, y: 18, size: 2,   o: 0.75 },
  { x:  8, y: 26, size: 1,   o: 0.4 },
  { x: 22, y: 30, size: 1.5, o: 0.55 },
  { x: 35, y: 28, size: 1,   o: 0.4 },
  { x: 48, y: 32, size: 2,   o: 0.65 },
  { x: 60, y: 26, size: 1,   o: 0.4 },
  { x: 73, y: 30, size: 1.5, o: 0.55 },
  { x: 86, y: 28, size: 1,   o: 0.45 },
  { x: 16, y: 38, size: 1,   o: 0.3 },
  { x: 42, y: 40, size: 1.5, o: 0.4 },
  { x: 68, y: 38, size: 1,   o: 0.3 },
  { x: 92, y: 42, size: 1.5, o: 0.4 },
  { x:  6, y: 14, size: 1,   o: 0.5 },
  { x: 30, y: 16, size: 1,   o: 0.45 },
];

function Starfield() {
  return (
    <svg
      aria-hidden
      viewBox="0 0 100 50"
      preserveAspectRatio="none"
      className="absolute inset-x-0 top-0 h-1/2 w-full pointer-events-none"
    >
      {STARS.map((s, i) => (
        <circle
          key={i}
          cx={s.x}
          cy={s.y}
          r={s.size * 0.15}
          fill="white"
          opacity={s.o}
        />
      ))}
    </svg>
  );
}

/* ----------------------------- rocket svg ------------------------------ */

/** The Pebble brand mark as a rocket. A vertically-oriented pebble
    silhouette with a subtle highlight on the upper-left (gives it dimension)
    and a small fire flicker at the base. Color uses currentColor so the
    parent controls it (we paint it the foreground charcoal). */
function PebbleRocket({ className = "" }: { className?: string }) {
  return (
    <svg
      viewBox="0 0 80 110"
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      aria-hidden
    >
      {/* Exhaust flicker — outer cone */}
      <motion.path
        d="M22 92 L40 110 L58 92 Z"
        fill="#3054ff"
        opacity={0.55}
        animate={{ scaleY: [1, 1.18, 1], opacity: [0.5, 0.7, 0.5] }}
        transition={{ duration: 0.5, repeat: Infinity, ease: "easeInOut" }}
        style={{ originY: 0 }}
      />
      {/* Exhaust flicker — inner core */}
      <motion.path
        d="M28 90 L40 104 L52 90 Z"
        fill="#ff7a3a"
        opacity={0.85}
        animate={{ scaleY: [1, 1.3, 1] }}
        transition={{ duration: 0.32, repeat: Infinity, ease: "easeInOut" }}
        style={{ originY: 0 }}
      />
      {/* Pebble body — vertical oval, brand foreground */}
      <ellipse
        cx="40"
        cy="46"
        rx="28"
        ry="42"
        fill="currentColor"
      />
      {/* Highlight on upper-left for dimension */}
      <ellipse
        cx="30"
        cy="28"
        rx="9"
        ry="14"
        fill="rgba(255,255,255,0.18)"
      />
      {/* Pebble accent dot — the brand "." */}
      <circle cx="40" cy="46" r="3" fill="#3054ff" opacity={0.85} />
    </svg>
  );
}

/* =====================================================================
   Main section
   ===================================================================== */

export interface TakeoffMomentProps {
  /** Scroll target for the chevron CTA. Defaults to the page-pricing
      anchor; pass nothing in most cases. */
  scrollTo?: string;
  className?: string;
}

export function TakeoffMoment({ scrollTo = "#pricing", className = "" }: TakeoffMomentProps) {
  const prefersReduced = useReducedMotion() ?? false;
  const containerRef = React.useRef<HTMLDivElement>(null);
  const [launched, setLaunched] = React.useState(false);

  // Fire the launch when the section enters view (once). With reduced-
  // motion on, jump straight to the post-launch end state — rocket
  // hidden, trail full-height, chevron pulsing — so the visual gravity
  // toward pricing still reads.
  React.useEffect(() => {
    if (prefersReduced) { setLaunched(true); return; }
    if (typeof window === "undefined" || !containerRef.current) return;
    const io = new IntersectionObserver(
      (entries) => {
        for (const e of entries) {
          if (e.isIntersecting) {
            setLaunched(true);
            io.disconnect();
          }
        }
      },
      { threshold: 0.35 },
    );
    io.observe(containerRef.current);
    return () => io.disconnect();
  }, [prefersReduced]);

  const handleScroll = () => {
    if (!scrollTo) return;
    const target = document.querySelector(scrollTo) as HTMLElement | null;
    target?.scrollIntoView({ behavior: "smooth", block: "start" });
  };

  return (
    <div
      ref={containerRef}
      className={cn(
        "relative w-full h-full overflow-hidden",
        "bg-gradient-to-b from-[#0e1230] via-[#3b4d7a] via-50% to-background",
        className,
      )}
    >
      <Starfield />

      {/* Vapor trail — tall thin column from the bottom-center growing
          up to where the rocket exits. Linear gradient fades to
          transparent at the top so it doesn't look like a hard line. */}
      <motion.div
        aria-hidden
        initial={{ height: prefersReduced ? "82%" : 0, opacity: prefersReduced ? 0.8 : 0 }}
        animate={launched ? { height: "82%", opacity: 0.8 } : { height: 0, opacity: 0 }}
        transition={{
          height:  { duration: LAUNCH_MS / 1000, ease: EASE, delay: prefersReduced ? 0 : 0.4 },
          opacity: { duration: 0.35,                ease: EASE, delay: prefersReduced ? 0 : 0.45 },
        }}
        className="absolute left-1/2 -translate-x-1/2 bottom-0 w-[6px] sm:w-[8px] rounded-t-full pointer-events-none"
        style={{
          background:
            "linear-gradient(to top, rgba(255,255,255,0.6) 0%, rgba(255,180,140,0.45) 30%, rgba(255,200,200,0.18) 70%, rgba(255,255,255,0) 100%)",
          filter: "blur(0.5px)",
        }}
      />

      {/* The rocket itself — Pebble brand mark, lifts off from bottom-
          center to off-screen top. Hidden in the reduced-motion end
          state (already gone). */}
      <motion.div
        aria-hidden
        initial={{ y: prefersReduced ? "-110%" : "10%", opacity: prefersReduced ? 0 : 1 }}
        animate={
          launched
            ? { y: "-110%", opacity: prefersReduced ? 0 : [1, 1, 0.95, 0] }
            : { y: "10%", opacity: 1 }
        }
        transition={{
          y:       { duration: LAUNCH_MS / 1000, ease: EASE, delay: prefersReduced ? 0 : 0.4 },
          opacity: { duration: LAUNCH_MS / 1000, ease: "easeIn", delay: prefersReduced ? 0 : 0.4, times: [0, 0.6, 0.85, 1] },
        }}
        className="absolute left-1/2 -translate-x-1/2 bottom-[28%] sm:bottom-[24%] text-foreground"
      >
        <PebbleRocket className="w-14 h-20 sm:w-20 sm:h-28" />
      </motion.div>

      {/* Foreground copy — fades in just before the rocket fires. */}
      <div className="absolute inset-0 flex flex-col items-center justify-center text-center px-4 max-w-2xl mx-auto pointer-events-none">
        <motion.h2
          initial={{ opacity: 0, y: 12 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.7, ease: EASE, delay: TEXT_DELAY_MS / 1000 }}
          className="font-[family-name:var(--font-cormorant)] italic text-4xl sm:text-6xl lg:text-7xl text-white drop-shadow-[0_4px_24px_rgba(0,0,0,0.4)]"
        >
          Ready for takeoff?
        </motion.h2>
        <motion.p
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, ease: EASE, delay: (TEXT_DELAY_MS + 250) / 1000 }}
          className="mt-4 text-base sm:text-lg text-white/85 drop-shadow"
        >
          Pick a plan. We&apos;ll handle the rest.
        </motion.p>
      </div>

      {/* Scroll-down cue — appears after launch, pulses to signal
          "keep going, pricing is below." Clickable for kbd users +
          anyone who wants the assist. */}
      <motion.button
        type="button"
        onClick={handleScroll}
        initial={{ opacity: 0, y: -6 }}
        animate={launched ? { opacity: 1, y: 0 } : { opacity: 0, y: -6 }}
        transition={{ duration: 0.5, ease: EASE, delay: (LAUNCH_MS + 200) / 1000 }}
        aria-label="Scroll to pricing"
        className={cn(
          "absolute left-1/2 -translate-x-1/2 bottom-6 sm:bottom-8",
          "inline-flex flex-col items-center gap-1 text-white/75 hover:text-white",
          "text-[10px] uppercase tracking-[0.18em] font-semibold",
          "transition-colors duration-200",
          "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white/60 focus-visible:ring-offset-2 focus-visible:ring-offset-[#0e1230] rounded-md px-2 py-1",
        )}
      >
        <span>Pricing below</span>
        <motion.span
          animate={prefersReduced ? {} : { y: [0, 4, 0] }}
          transition={{ duration: 1.4, repeat: Infinity, ease: "easeInOut" }}
        >
          <ChevronDown className="w-5 h-5" aria-hidden />
        </motion.span>
      </motion.button>
    </div>
  );
}

export default TakeoffMoment;
