"""Cross-cutting security primitives shared across handlers.

Five things live here:

1. ``validate_slug`` — accept slugs only when they're a-z0-9-_, 1..100
   chars. Without this, a slug from the URL like ``../../etc/passwd``
   would resolve through ``OUTPUT_DIR / slug`` to somewhere outside the
   output directory. Flagged Tier-1 by the 2026-05-15 evening NLM pass.
2. ``require_project_owner`` — gate read/write project routes behind
   ownership. The current rule mirrors ``run_list_projects``: a logged-in
   user can touch their own projects + any unclaimed (legacy) project;
   nothing else. Now also calls ``validate_slug`` first.
3. ``project_lock`` — per-slug mutex covering refine + visual-edit +
   block-insert + rollback. Without this, two concurrent mutations
   race: both snapshot the same pre-state, both write, the second
   clobbers the first AND its snapshot bakes in the first write.
4. ``client_ip`` — resolve the client IP with explicit trust of
   ``X-Forwarded-For`` only when the immediate peer is in
   ``PEBBLE_TRUSTED_PROXIES``. Without that config, header values are
   ignored — eliminates the rate-limit-bypass and analytics-poisoning
   vectors NotebookLM flagged.
5. ``RateLimiter`` — in-memory token bucket keyed by anything (IP, email,
   slug). Sub-second precision, decays automatically, defaults to closed
   when the bucket is empty.
"""
from __future__ import annotations

import ipaddress
import json
import os
import re
import sys
import threading
import time
from contextlib import contextmanager
from pathlib import Path
from typing import Iterator, Optional


# --------- Slug validation ------------------------------------------------

# Engine slugs are generated by ``_slugify`` which produces lowercase
# alphanumeric + hyphen. We accept the same shape on the way IN (with a
# small underscore tolerance for legacy projects) so a URL-supplied slug
# can never escape the output dir via ``../`` or contain shell-meta.
_SLUG_RE = re.compile(r"^[a-z0-9][a-z0-9_-]{0,99}$")
# Snapshot IDs are written by pebble.history.snapshot_site as
# "YYYYMMDDTHHMMSS-<reason>" — the literal `T` and digits force the
# capital-T allowance; reasons add hyphens and lowercase letters.
_SNAPSHOT_ID_RE = re.compile(r"^[0-9]{8}T[0-9]{6}[A-Za-z0-9_-]{0,100}$")
# User IDs (Supabase UUIDs in practice) — alphanumerics + hyphen/underscore.
# Tight enough that ``../victim``-style traversal can never reach
# `OUTPUT_DIR / .users / <uid>` and walk out. Matches engagement.py and
# stripe_webhook.py's local copies; this is the canonical version that
# the billing readers + future modules should depend on.
_USER_ID_RE = re.compile(r"^[A-Za-z0-9_-]{1,128}$")
# Windows reserved device names — `CON.json` writes to the console, `NUL`
# silently discards, etc. Block them so a future identity provider that
# returns short non-UUID ids can't collide.
_WINDOWS_RESERVED_NAMES = frozenset(
    {"con", "nul", "aux", "prn"}
    | {f"com{i}" for i in range(1, 10)}
    | {f"lpt{i}" for i in range(1, 10)}
)


def safe_user_id(raw: object) -> str:
    """Return ``raw`` normalized to lowercase if it's a safe user-id, else ``""``.

    Used by any module that interpolates a Supabase user-id into a
    filesystem path under ``output/.users/<uid>/...``. Without this,
    ``../victim`` would resolve through ``OUTPUT_DIR/.users/<raw>/`` to
    a sibling directory the attacker can read.

    NOT a substitute for parameterized queries / proper escaping; this is
    SPECIFICALLY the filesystem-path safety check. Returns ``""`` on any
    invalid input so callers can ``if not safe_user_id(x): return None``.

    Identity-provider assumption (NLM round 3 R3.B1)
    ------------------------------------------------
    The ``.lower()`` step assumes the identity provider treats user IDs as
    case-INSENSITIVE — i.e. ``USER1`` and ``user1`` refer to the same
    account. Supabase Auth satisfies this: it mints UUID v4 in lowercase
    hex and stores them as-is. If Pebble ever swaps identity providers
    to one that treats case as significant (Auth0 with custom IDs, some
    SAML IdPs), two distinct users with names differing only in case
    would collide on the same sentinel directory and share billing
    state. Revisit this normalization at that point — likely solution
    is hashing the user-id into a fixed-shape directory name and
    embedding the exact original id inside the sentinel JSON.
    """
    if not isinstance(raw, str) or not raw:
        return ""
    if not _USER_ID_RE.fullmatch(raw):
        return ""
    lower = raw.lower()
    if lower in _WINDOWS_RESERVED_NAMES:
        return ""
    return lower


def is_valid_slug(slug: str) -> bool:
    """True when ``slug`` matches the engine's _slugify output shape AND
    contains no path-traversal segments. Pure-string check — no I/O."""
    if not isinstance(slug, str) or not slug:
        return False
    if not _SLUG_RE.match(slug):
        return False
    # _SLUG_RE already rejects '.', '/', and '\\' but be explicit:
    return ".." not in slug and "/" not in slug and "\\" not in slug


def is_valid_snapshot_id(snapshot_id: str) -> bool:
    """True when ``snapshot_id`` matches snapshot_site's emitted shape.
    Used by /api/rollback before composing a filesystem path with it.

    Examples of valid IDs:
        20260515T133057-generate
        20260515T133057-refine-friendlier
        20260515T133057-insert-block-faq
    """
    if not isinstance(snapshot_id, str) or not snapshot_id:
        return False
    if not _SNAPSHOT_ID_RE.match(snapshot_id):
        return False
    return ".." not in snapshot_id and "/" not in snapshot_id and "\\" not in snapshot_id


def validate_slug(handler, slug: str) -> bool:
    """Slug guard for HTTP handlers. Returns True on success; on failure
    writes a 400 to the handler and returns False so the caller can
    just ``if not validate_slug(...): return``."""
    if is_valid_slug(slug):
        return True
    handler._json(400, {"error": "invalid project slug"})
    return False


def validate_snapshot_id(handler, snapshot_id: str) -> bool:
    """Snapshot-id guard. Same contract as :func:`validate_slug`."""
    if is_valid_snapshot_id(snapshot_id):
        return True
    handler._json(400, {"error": "invalid snapshot id"})
    return False


# --------- Per-slug write lock --------------------------------------------

_PROJECT_LOCKS_MUTEX = threading.Lock()
_PROJECT_LOCKS: dict[str, threading.Lock] = {}

# --------- Per-user publish lock ------------------------------------------
# Prevents the TOCTOU race where two concurrent publish requests from the
# same user both pass the free-tier site-count check before either writes
# the publish.json that would make them visible to the counter.

_USER_PUBLISH_LOCKS_MUTEX = threading.Lock()
_USER_PUBLISH_LOCKS: dict[str, threading.Lock] = {}


def _get_user_publish_lock(user_id: str) -> threading.Lock:
    with _USER_PUBLISH_LOCKS_MUTEX:
        lock = _USER_PUBLISH_LOCKS.get(user_id)
        if lock is None:
            lock = threading.Lock()
            _USER_PUBLISH_LOCKS[user_id] = lock
        return lock


@contextmanager
def user_publish_lock(user_id: str, *, timeout: float = 60.0) -> Iterator[bool]:
    """Acquire the per-user mutex around the publish-limit check + publish.

    Prevents two concurrent publish requests from the same user from both
    passing the free-tier site-count check before either writes publish.json.
    Yields ``True`` when acquired, ``False`` on timeout (caller should 503).
    """
    lock = _get_user_publish_lock(user_id)
    acquired = lock.acquire(timeout=timeout)
    try:
        yield acquired
    finally:
        if acquired:
            lock.release()


def _get_project_lock(slug: str) -> threading.Lock:
    """Return (and lazily allocate) the lock for one project slug. The
    map grows by one entry per distinct slug — small enough we don't
    need expiry, and any stale entry just sits idle costing 24 bytes."""
    with _PROJECT_LOCKS_MUTEX:
        lock = _PROJECT_LOCKS.get(slug)
        if lock is None:
            lock = threading.Lock()
            _PROJECT_LOCKS[slug] = lock
        return lock


@contextmanager
def project_lock(slug: str, *, timeout: float = 30.0) -> Iterator[bool]:
    """Acquire the per-slug mutex around a mutation. Use around
    snapshot + write blocks so concurrent refine/visual-edit/block-insert
    requests can't race on the same project.

    Yields ``True`` when the lock was acquired, ``False`` on timeout.
    Callers should treat ``False`` as "another mutation is in flight,
    reject the request" rather than waiting forever.
    """
    lock = _get_project_lock(slug)
    acquired = lock.acquire(timeout=timeout)
    try:
        yield acquired
    finally:
        if acquired:
            lock.release()


# --------- Project ownership ----------------------------------------------

def _output_dir() -> Path:
    eng = sys.modules.get("pebble_engine") or sys.modules.get("__main__")
    if eng and hasattr(eng, "OUTPUT_DIR"):
        return Path(getattr(eng, "OUTPUT_DIR"))
    return Path(__file__).parent.parent.resolve() / "output"


def _project_owner(slug: str) -> Optional[str]:
    """Return the _user_id stamped in the project's brief, or None for
    unclaimed projects (no brief or no _user_id field)."""
    p = _output_dir() / slug / "brief.json"
    if not p.exists():
        return None
    try:
        brief = json.loads(p.read_text(encoding="utf-8"))
    except Exception:
        return None
    owner = brief.get("_user_id")
    return owner if isinstance(owner, str) and owner else None


def require_user(handler) -> Optional[dict]:
    """Auth gate for user-level endpoints (billing, account settings).

    Returns the validated Supabase user dict (``{'id', 'email', ...}``) on
    success. Writes the appropriate HTTP error and returns None otherwise.

    Sister to :func:`require_project_owner`, which adds an ownership check
    on top. Use this when the endpoint operates on the caller themselves
    rather than a project they own.

    Status codes:
    - 401 — no/malformed Authorization header, or token rejected by GoTrue
    - 503 — Supabase not configured on this instance, or GoTrue unreachable
    """
    raw = (handler.headers.get("Authorization", "") or "").strip()
    # Case-insensitive scheme per RFC 6750 — a "bearer" / "BEARER" prefix is
    # equivalent to "Bearer".
    if not raw.lower().startswith("bearer "):
        handler._json(401, {"error": "sign in required"})
        return None
    token = raw[7:].strip()
    if not token:
        handler._json(401, {"error": "sign in required"})
        return None

    # Lazy import so test_security.py (which heavily monkeypatches
    # auth_admin) doesn't pay GoTrue's network imports at module load.
    try:
        from pebble import auth_admin
    except Exception:
        handler._json(500, {"error": "auth subsystem unavailable"})
        return None

    if not auth_admin.is_configured():
        handler._json(503, {"error": "auth not configured on this Pebble instance"})
        return None

    try:
        user = auth_admin.validate_access_token(token)
    except auth_admin.AdminError:
        # NLM round on Track 12 documented why this must be 503 and not 401:
        # a transient GoTrue outage would otherwise look identical to a bad
        # token to the v3 frontend, which would then log the user out.
        handler._json(503, {"error": "auth backend unavailable"})
        return None

    if not isinstance(user, dict) or not user.get("id"):
        handler._json(401, {"error": "sign in required"})
        return None

    return user


def resolve_user_id(handler) -> Optional[str]:
    """Resolve the calling user's id from EITHER auth path:

      1. ``Authorization: Bearer <jwt>`` — Supabase access token (what
         the v3 frontend sends).
      2. Legacy ``pebble_session`` cookie — homegrown auth, deprecated
         but still used by Python test fixtures.

    Returns ``None`` if neither identifies a valid user. NEVER writes
    to the handler — the caller decides what 'no user' means for its
    endpoint (401, empty list, etc.).

    Phase 58e (2026-05-22) — extracted from ``require_project_owner``
    so the project-listing and usage-summary endpoints (which never
    take a slug) can use the same Bearer-first/cookie-fallback chain.
    Without this, /api/projects and /api/usage were silently treating
    Bearer-authed v3 callers as logged-out, and showing them every
    user's projects + cost data. Found during the 2026-05-22 overnight
    bug hunt.
    """
    uid: Optional[str] = None
    raw_auth = (handler.headers.get("Authorization", "") or "").strip()
    if raw_auth.lower().startswith("bearer ") and len(raw_auth) > 7:
        try:
            from pebble import auth_admin
            if auth_admin.is_configured():
                try:
                    supabase_user = auth_admin.validate_access_token(raw_auth[7:].strip())
                    if isinstance(supabase_user, dict) and supabase_user.get("id"):
                        uid = supabase_user["id"]
                except auth_admin.AdminError:
                    # GoTrue unreachable — DON'T fail here, let the
                    # legacy cookie path try too. Only None out if both
                    # miss; the caller decides what to do with that.
                    pass
        except Exception:
            # auth_admin import / configuration check failed — fall through.
            pass

    if not uid:
        try:
            from pebble.server.auth import current_user_id
            uid = current_user_id(handler)
        except Exception:
            uid = None
    return uid


def require_project_owner(handler, slug: str) -> Optional[str]:
    """Return the calling user's id on success, otherwise respond and
    return None.

    Rules:
    - Slug fails shape check (path traversal, special chars): 400.
    - Caller not signed in: 401.
    - Project doesn't exist: 404.
    - Project has an owner that isn't the caller: 403.
    - Project unclaimed (no _user_id): allow — matches dashboard listing.
    """
    # Tier-1 fix from the 2026-05-15 evening NLM pass: a slug like
    # ``../config`` would otherwise resolve through ``OUTPUT_DIR / slug``
    # to a path outside the output directory, and ``.exists()`` would
    # cheerfully return True for any neighbor brief.json.
    if not validate_slug(handler, slug):
        return None
    project_dir = _output_dir() / slug
    if not project_dir.exists():
        handler._json(404, {"error": f"project not found: {slug}"})
        return None

    # Phase 58d (2026-05-22) — accept BOTH auth paths via the shared
    # resolver: Supabase Bearer JWT first (what v3 actually sends),
    # then legacy session cookie. Returns None on no/invalid auth.
    uid = resolve_user_id(handler)

    if not uid:
        handler._json(401, {"error": "sign in required"})
        return None
    owner = _project_owner(slug)
    if owner and owner != uid:
        handler._json(403, {"error": "not authorized for this project"})
        return None
    return uid


# --------- Trusted-proxy-aware client IP ----------------------------------

def _trusted_proxy_networks() -> list[ipaddress._BaseNetwork]:
    """Parse PEBBLE_TRUSTED_PROXIES (comma-separated CIDRs).

    Empty/unset = no trusted proxies, so X-Forwarded-For is ignored.
    """
    raw = os.environ.get("PEBBLE_TRUSTED_PROXIES", "") or ""
    out: list[ipaddress._BaseNetwork] = []
    for part in raw.split(","):
        s = part.strip()
        if not s:
            continue
        try:
            out.append(ipaddress.ip_network(s, strict=False))
        except Exception:
            continue
    return out


def _is_trusted_proxy(ip: str) -> bool:
    if not ip:
        return False
    try:
        addr = ipaddress.ip_address(ip)
    except Exception:
        return False
    for net in _trusted_proxy_networks():
        if addr in net:
            return True
    return False


_TRUSTED_PROXY_WARNING_LOGGED = False


def _maybe_warn_unconfigured_proxy(peer: Optional[str]) -> None:
    """Log ONCE if a request arrives with X-Forwarded-For but
    PEBBLE_TRUSTED_PROXIES is empty. The 2026-05-15 NLM pass flagged
    the deployment failure mode: behind a CDN, every request comes
    from one IP (the proxy) and our rate limits collapse to a global
    bucket. Operators need to be told once so they can configure the
    proxy ranges before deploy. After the first log we go silent to
    avoid filling the engine.log."""
    global _TRUSTED_PROXY_WARNING_LOGGED
    if _TRUSTED_PROXY_WARNING_LOGGED:
        return
    _TRUSTED_PROXY_WARNING_LOGGED = True
    try:
        from pebble.log import log
        log.warning(
            "X-Forwarded-For seen from %s but PEBBLE_TRUSTED_PROXIES is empty — "
            "rate limiters will treat all CDN traffic as one client. "
            "Set PEBBLE_TRUSTED_PROXIES=<cidr,cidr> in .env before deploy.",
            peer,
        )
    except Exception:
        pass


def client_ip(handler) -> Optional[str]:
    """Resolve the calling client's IP.

    Only honors ``X-Forwarded-For`` when the immediate peer is in
    ``PEBBLE_TRUSTED_PROXIES``. Otherwise returns the raw peer address.

    Logs ONCE when XFF is present but the proxy allow-list is empty —
    helps operators catch the misconfiguration before deploying behind
    a CDN.
    """
    try:
        peer = handler.client_address[0]
    except Exception:
        peer = None
    fwd = handler.headers.get("X-Forwarded-For") if hasattr(handler, "headers") else None
    if fwd and peer:
        if _is_trusted_proxy(peer):
            # XFF is "client, proxy1, proxy2"; the client is the left-most.
            first = fwd.split(",", 1)[0].strip()
            return first or peer
        if not _trusted_proxy_networks():
            _maybe_warn_unconfigured_proxy(peer)
    return peer


# --------- Rate limiter ----------------------------------------------------

class RateLimiter:
    """Token-bucket rate limiter keyed by an opaque string.

    ``allow(key)`` returns True if the request fits the current budget,
    False if it must be rejected. Tokens refill at ``rate`` per second,
    capped at ``burst``. Buckets idle for more than ``decay_seconds``
    are pruned on the next access.

    All state is in-memory; this is per-process. Pebble runs as one
    process so that's correct today. If we ever scale out, swap for
    a Redis-backed equivalent.
    """

    def __init__(self, *, rate: float, burst: int, decay_seconds: float = 600.0) -> None:
        if rate <= 0 or burst <= 0:
            raise ValueError("rate and burst must be positive")
        self._rate = float(rate)
        self._burst = int(burst)
        self._decay = float(decay_seconds)
        self._lock = threading.Lock()
        self._buckets: dict[str, tuple[float, float]] = {}  # key -> (tokens, last_refill_ts)

    def allow(self, key: str) -> bool:
        if not key:
            return True  # never block unkeyed callers (caller can short-circuit)
        now = time.monotonic()
        with self._lock:
            self._gc(now)
            tokens, last = self._buckets.get(key, (float(self._burst), now))
            # Refill
            elapsed = max(0.0, now - last)
            tokens = min(float(self._burst), tokens + elapsed * self._rate)
            if tokens >= 1.0:
                tokens -= 1.0
                self._buckets[key] = (tokens, now)
                return True
            self._buckets[key] = (tokens, now)
            return False

    def reset(self, key: str) -> None:
        with self._lock:
            self._buckets.pop(key, None)

    def _gc(self, now: float) -> None:
        # Cheap pass — only walks every ~100 accesses to avoid O(n) per call.
        if len(self._buckets) < 256:
            return
        cutoff = now - self._decay
        dead = [k for k, (_, t) in self._buckets.items() if t < cutoff]
        for k in dead:
            self._buckets.pop(k, None)


# Pre-built limiters used across handlers. Module-level so they share
# state across requests.
forms_submit_limiter   = RateLimiter(rate=1/6.0,    burst=10)    # 10 / minute, ~600 / hour burst-friendly
track_view_limiter     = RateLimiter(rate=2.0,      burst=20)    # 120 / minute / IP
forgot_email_limiter   = RateLimiter(rate=1/300.0,  burst=3)     # 3 then 1 / 5 min / email
# /api/inspire fetches arbitrary user-supplied URLs (network + 2MB read +
# parse). Tighter budget than form-submit because each request costs more.
inspire_fetch_limiter  = RateLimiter(rate=1/60.0,   burst=6)     # 6 burst, then 1 / minute / IP
# /api/generate and /api/generate-stream each trigger a full LLM call
# (~$0.30–3.00). 5-burst lets a developer iterate quickly; 1/2-min sustained
# keeps a single IP to ~35 builds/hour max — still costly but not unlimited.
generate_limiter       = RateLimiter(rate=1/120.0,  burst=5)     # 5 burst, then 1 / 2 min / IP
# /api/plan is cheap (no LLM call) but we still cap it to prevent enumeration
# of industry intel + DNA combinations.
plan_limiter           = RateLimiter(rate=1/10.0,   burst=20)    # 20 burst, then 1 / 10 sec / IP


__all__ = [
    "RateLimiter",
    "client_ip",
    "require_project_owner",
    "forms_submit_limiter",
    "track_view_limiter",
    "forgot_email_limiter",
    "inspire_fetch_limiter",
    "generate_limiter",
    "plan_limiter",
]
