"""Bot persona endpoint — Phase 25b (2026-05-20).

Webild's perceived-speed magic isn't just the plan reveal — it's the
warm, conversational "Bob is thinking..." → "Bob is building..." → "I
finished the hero, working on services now" narration that runs
alongside the build. That narration is generated by a separate cheap
LLM call (Webild has `/api/generate-loading-messages` — we caught it
during the teardown).

This is the same pattern. ONE endpoint, several intent types:

- ``greeting``: 1-2 sentence warm opener when a build starts. Names
  the business, sets expectations. Replaces the silent "Building..."
  spinner Marc rightly complained about.
- ``status``: mid-build narration ("I picked your style", "Writing
  pages now", etc.). 1 sentence per phase. Fires from the SSE event
  handler.
- ``chips``: 3 short follow-up actions for the user to click after
  the build is done ("Strengthen Hero Headline", "Add Clearer CTA").

Cost target: ~$0.0001 per call via GPT-4o-mini through OpenRouter.
At 20 calls per build × 1,000 builds/month, that's ~$2/mo. Negligible.

The v3 frontend integration is a separate slice — this module just
ships the endpoint + tests so the frontend can call it.
"""
from __future__ import annotations

import json
from typing import Any

from pebble.log import log
from pebble.security import client_ip, plan_limiter


# Cheap chat model. Hardcoded for now; Phase 28 will wire intent-based
# model routing through pebble/llm.py. Using OpenRouter so it works
# with the existing OPENROUTER_API_KEY — no new env vars needed.
BOT_CHAT_MODEL = "openai/gpt-4o-mini"
BOT_CHAT_MAX_TOKENS = 200


# ---------------------------------------------------------------------------
# Intent → prompt mapping
# ---------------------------------------------------------------------------
#
# Keep system prompts tiny. The cheap chat LLM does well with focused
# 1-sentence instructions and a clear output shape.


def _system_for(intent: str) -> str:
    if intent == "greeting":
        return (
            "You are Pebble, a warm website-building assistant. Greet the "
            "user in 1-2 sentences when they submit a new build. Be specific "
            "about what you're going to build (use the business_name and "
            "business_type from the context). Conversational, not corporate. "
            "Don't use exclamation points. Don't promise specific times. "
            "Don't invent details not in the context. Return plain text, no "
            "markdown, no quotes around the message."
        )
    if intent == "status":
        return (
            "You are Pebble, narrating your own work while a website builds. "
            "The user sent you a build for {business_name}. You just finished "
            "the step described in `context.phase`. Write 1 short sentence "
            "(under 90 chars) describing what you just did, in first person, "
            "conversational. No exclamation points. Plain text, no markdown."
        )
    if intent == "chips":
        return (
            "You are Pebble. The user's website build just finished. Suggest "
            "exactly 3 short follow-up actions they could ask you to take "
            "next, like 'Strengthen Hero Headline' or 'Add Clearer CTA'. "
            "Output ONLY a JSON array of 3 strings, each under 40 chars, "
            "title-cased, action verbs. Example output: "
            '["Strengthen Hero Headline", "Add Trust Section", "Change Color Palette"]'
        )
    # Fallback for unknown intents — keep the endpoint flexible but safe.
    return (
        "You are Pebble, a helpful website-building assistant. Respond "
        "briefly and warmly to whatever context is provided. Plain text."
    )


def _user_message_for(intent: str, context: dict[str, Any]) -> str:
    """Render the per-call user message from the context dict. The shape
    differs per intent — keep one place so the API contract is obvious."""
    bn = (context.get("business_name") or "").strip() or "Untitled"
    bt = (context.get("business_type") or "").strip() or "business"
    if intent == "greeting":
        return (
            f"business_name: {bn}\n"
            f"business_type: {bt}\n"
            "Give the greeting now."
        )
    if intent == "status":
        phase = (context.get("phase") or "started").strip()
        return (
            f"business_name: {bn}\n"
            f"phase: {phase}\n"
            "Write the 1-sentence status update now."
        )
    if intent == "chips":
        return (
            f"business_name: {bn}\n"
            f"business_type: {bt}\n"
            "Return the 3-action JSON array now."
        )
    return json.dumps(context, ensure_ascii=False)


# ---------------------------------------------------------------------------
# Endpoint
# ---------------------------------------------------------------------------


def _extract_chips_array(raw: str) -> list[str]:
    """LLM may wrap the JSON array in markdown fences, prose, or trailing
    explanation. Pull the first JSON array of strings out of the text."""
    import re
    m = re.search(r"\[[^\[\]]*\]", raw, re.DOTALL)
    if not m:
        return []
    try:
        parsed = json.loads(m.group(0))
        if isinstance(parsed, list):
            return [str(x).strip() for x in parsed if isinstance(x, (str, int))][:3]
    except Exception:
        pass
    return []


def run_bot_message(handler) -> None:
    """POST /api/bot-message
    Body: {intent: "greeting" | "status" | "chips", context: {...}}
    Returns: {message: str} for greeting/status,
             {chips: [str, str, str]} for chips
    """
    ip = client_ip(handler)
    # Use plan limiter (lighter than build) — these are cheap, frequent calls.
    if not plan_limiter.allow(ip or ""):
        handler._json(429, {"error": "too many bot messages — try again in a moment"})
        return

    try:
        length = int(handler.headers.get("Content-Length", "0"))
    except ValueError:
        handler._json(400, {"error": "invalid Content-Length header"})
        return
    if length <= 0 or length > 16384:
        handler._json(400, {"error": "missing or oversized body"})
        return
    try:
        body = json.loads(handler.rfile.read(length).decode("utf-8"))
    except Exception:
        handler._json(400, {"error": "invalid json"})
        return

    intent = (body.get("intent") or "").strip().lower()
    context = body.get("context") or {}
    if intent not in {"greeting", "status", "chips"}:
        handler._json(400, {"error": f"unsupported intent {intent!r}"})
        return
    if not isinstance(context, dict):
        handler._json(400, {"error": "context must be an object"})
        return

    system = _system_for(intent)
    user = _user_message_for(intent, context)

    # Build an isolated client targeting the cheap chat model — independent
    # of PEBBLE_MODEL so we never accidentally route greeting calls through
    # an expensive build model.
    try:
        import os
        from pebble.llm import OpenRouterClient
        api_key = os.environ.get("OPENROUTER_API_KEY", "").strip()
        if not api_key:
            raise RuntimeError("OPENROUTER_API_KEY not set")
        client = OpenRouterClient(api_key=api_key, model=BOT_CHAT_MODEL)
        raw = client.generate(system=system, user=user, max_tokens=BOT_CHAT_MAX_TOKENS)
        text = raw if isinstance(raw, str) else getattr(raw, "text", "")
    except Exception as e:
        log.warning("[bot-message] %s call failed: %s", intent, e)
        # Degrade gracefully — return a safe canned response rather than 500ing.
        # The whole point of this endpoint is to make the UI feel alive; a
        # safe fallback is better than no message.
        fallbacks = {
            "greeting": "I'm getting started on your build.",
            "status": "Working on the next part of your site.",
            "chips": ["Refine Hero", "Add a Section", "Change Palette"],
        }
        if intent == "chips":
            handler._json(200, {"chips": fallbacks["chips"], "fallback": True})
        else:
            handler._json(200, {"message": fallbacks[intent], "fallback": True})
        return

    if intent == "chips":
        chips = _extract_chips_array(text)
        if not chips:
            chips = ["Refine Hero", "Add a Section", "Change Palette"]
        handler._json(200, {"chips": chips})
        return

    # Greeting + status return a plain message. Strip surrounding quotes/
    # whitespace LLMs sometimes add.
    cleaned = (text or "").strip().strip('"').strip("'").strip()
    if not cleaned:
        cleaned = "Working on your site."
    handler._json(200, {"message": cleaned})


__all__ = ["run_bot_message", "BOT_CHAT_MODEL"]
