"""Single-source env propagation — 2026-05-24.

Pebble has 3 places .env values are read from:

  1. /c/Users/marci/pebble-engine/.env                    (parent worktree, master)
  2. /c/Users/marci/pebble-engine/.claude/worktrees/*/.env (per-worktree copies)
  3. /c/Users/marci/pebble-engine/ui/v3/.env.local         (browser-public vars only)

Each git worktree gets its OWN .env file (the parent's isn't shared
automatically). Next.js requires its env in the app directory and only
exposes vars prefixed with NEXT_PUBLIC_ to the browser.

Marc's pain: he edits the parent .env, but every worktree (including
the one Claude runs in) needs the same values, AND ui/v3/.env.local
needs the NEXT_PUBLIC_* subset. Without this script, every key change
requires editing 3+ files by hand or running the engine from a
worktree that's silently out-of-sync.

This script makes the parent's `.env` the single source of truth:

  - Reads the parent's .env
  - Overwrites every worktree's .env with the parent's content
    (including the parent's own — no-op when already in sync)
  - Overwrites every worktree's ui/v3/.env.local with the same content
    (Next.js naturally filters NEXT_PUBLIC_* into the browser bundle;
    server-only keys stay server-only, so full-copy is safe and
    eliminates "did I forget to add a key" footguns)

Usage:
  python scripts/sync_env.py            # do the sync, print what changed
  python scripts/sync_env.py --dry-run  # show what WOULD change, write nothing
  python scripts/sync_env.py --quiet    # write silently, only print errors

Idempotent. Safe to run repeatedly. Wired into ui/v3/package.json as a
`predev` script so `npm run dev` auto-syncs first.

Why Python instead of PowerShell: works the same on macOS / WSL /
remote Linux box if Marc ever moves the dev environment.
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path


# Master location relative to this script: scripts/ is at the worktree root.
# The parent worktree's .env is two levels up from the worktree's .env
# location when we're in a worktree, or just at "../.." when running from
# inside ui/v3 (the predev path). We resolve absolute from the script's
# own path to be position-independent.
_SCRIPT_PATH = Path(__file__).resolve()
_WORKTREE_ROOT = _SCRIPT_PATH.parent.parent  # scripts/sync_env.py → worktree root

# The parent project root: the .git directory in a worktree is a FILE
# (not a directory) pointing back to the parent's .git via `gitdir:`. We
# resolve that to find the true master worktree.
def _find_parent_root(worktree_root: Path) -> Path:
    """Return the parent (main) worktree root by inspecting .git.

    A worktree's .git is a plain file with content like:
        gitdir: /c/Users/marci/pebble-engine/.git/worktrees/<name>
    From that, the parent's .git directory is /c/Users/marci/pebble-engine/.git
    so the parent worktree root is /c/Users/marci/pebble-engine.

    If .git is already a directory (we ARE the parent), return ourselves.
    """
    git_path = worktree_root / ".git"
    if git_path.is_dir():
        return worktree_root  # we ARE the main worktree
    if not git_path.is_file():
        return worktree_root  # not in a git checkout, fall through
    try:
        content = git_path.read_text(encoding="utf-8").strip()
    except Exception:
        return worktree_root
    if not content.startswith("gitdir:"):
        return worktree_root
    gitdir = Path(content.split(":", 1)[1].strip())
    # gitdir like .git/worktrees/<name>; parent's .git is its grandparent.
    # parent .git is at gitdir.parent.parent (...../.git/worktrees/<name>
    # → ...../.git → ...... <- parent worktree root)
    if "worktrees" in gitdir.parts:
        parent_git = gitdir.parent.parent
        return parent_git.parent
    return worktree_root


PARENT_ROOT = _find_parent_root(_WORKTREE_ROOT)
MASTER_ENV  = PARENT_ROOT / ".env"

# Sync targets: every worktree (parent + .claude/worktrees/*) gets:
#   - its own .env       ← full master copy
#   - its own ui/v3/.env.local ← full master copy + header
WORKTREES_DIR = PARENT_ROOT / ".claude" / "worktrees"


_V3_HEADER = """\
# AUTO-GENERATED by scripts/sync_env.py — DO NOT EDIT BY HAND.
# Source: /pebble-engine/.env  (full copy — Next.js bundles only
# NEXT_PUBLIC_* into the browser, so server-only secrets stay
# server-only here).
# To change a value: edit the MASTER .env at the project root, then
# run `python scripts/sync_env.py` (or just `npm run dev` — it
# auto-syncs via the predev hook).
"""


def _write_if_changed(target: Path, content: str, *, dry_run: bool, quiet: bool) -> bool:
    """Write content to target if it differs. Returns True if a write
    happened (or would happen in dry-run mode)."""
    existing = target.read_text(encoding="utf-8", errors="replace") if target.is_file() else ""
    if existing == content:
        return False
    if dry_run:
        if not quiet:
            print(f"  WOULD UPDATE: {target}")
        return True
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")
    if not quiet:
        print(f"  updated: {target}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dry-run", action="store_true", help="show what would change, write nothing")
    parser.add_argument("--quiet",   action="store_true", help="suppress per-file output (errors still print)")
    args = parser.parse_args()

    if not MASTER_ENV.is_file():
        # No master .env (CI/Vercel build, fresh clone, or first-run dev).
        # That's NOT an error — env vars on those platforms come from the
        # platform's own variable config, not a checked-in file. We only
        # exit 1 if --strict is passed (e.g. for explicit Marc-side audits
        # where a missing master env IS a misconfiguration).
        msg = f"sync_env.py: no master .env at {MASTER_ENV} — nothing to sync."
        if not args.quiet:
            print(msg, file=sys.stderr)
        return 0

    master_content = MASTER_ENV.read_text(encoding="utf-8", errors="replace")
    v3_content     = _V3_HEADER + master_content

    if not args.quiet:
        line_count = master_content.count("\n") + 1
        print(f"sync_env: master = {MASTER_ENV}")
        print(f"          ({line_count} lines, {len(master_content)} bytes)")

    changes = 0

    # Collect all the worktree roots we should sync to. The parent
    # worktree is always included (so its own .env stays in sync — a
    # no-op since IT is the master, but the parent's ui/v3/.env.local
    # DOES need the header + master copy).
    worktree_roots: list[Path] = [PARENT_ROOT]
    if WORKTREES_DIR.is_dir():
        for wt in sorted(WORKTREES_DIR.iterdir()):
            if wt.is_dir():
                worktree_roots.append(wt)

    for wt in worktree_roots:
        # 1. Worktree .env — full master copy (no header — the engine
        #    treats # lines as comments fine but a header would just
        #    add noise to a file Marc edits in the parent).
        wt_env = wt / ".env"
        # Only sync if .env already exists (don't create one in dormant
        # worktrees — that's a signal the worktree hasn't been used).
        # EXCEPTION: parent worktree always syncs even though it IS the
        # master (no-op write that exercises the codepath).
        if wt == PARENT_ROOT or wt_env.exists():
            if _write_if_changed(wt_env, master_content,
                                 dry_run=args.dry_run, quiet=args.quiet):
                changes += 1
        elif not args.quiet:
            print(f"  skipping (no .env): {wt_env}")

        # 2. Worktree ui/v3/.env.local — full master copy + header.
        #    Only sync if ui/v3 exists in this worktree (not every
        #    worktree carries the v3 frontend).
        v3_local = wt / "ui" / "v3" / ".env.local"
        if (wt / "ui" / "v3").is_dir():
            if _write_if_changed(v3_local, v3_content,
                                 dry_run=args.dry_run, quiet=args.quiet):
                changes += 1

    if not args.quiet:
        if args.dry_run:
            print(f"\ndry-run: {changes} file(s) WOULD be updated")
        else:
            print(f"\nsync complete: {changes} file(s) updated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
